image:
  repository: <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/payment
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 2
namespace: payment
service:
  port: 3004
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
pdb:
  enabled: true
  minAvailable: 1
bluegreen:
  slot: blue   # toggled by deploy-bluegreen.sh -> green
