apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.bluegreen.slot }}
  namespace: {{ .Values.namespace }}
  labels: { app: {{ .Chart.Name }}, slot: {{ .Values.bluegreen.slot }} }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ .Chart.Name }}, slot: {{ .Values.bluegreen.slot }} }
  template:
    metadata:
      labels: { app: {{ .Chart.Name }}, slot: {{ .Values.bluegreen.slot }} }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: {{ .Values.service.port }} }]
          env:
            - { name: CONSUL_HOST, value: "consul-server.consul.svc.cluster.local" }
            - { name: POD_IP, valueFrom: { fieldRef: { fieldPath: status.podIP } } }
          readinessProbe: { httpGet: { path: /ready,  port: {{ .Values.service.port }} }, initialDelaySeconds: 3 }
          livenessProbe:  { httpGet: { path: /health, port: {{ .Values.service.port }} }, initialDelaySeconds: 10 }
          resources: {{ toYaml .Values.resources | nindent 12 }}
