name: CI

on:
  pull_request:
  push: { branches: [main] }

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user, product, order, payment, notification]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install + test
        working-directory: services/${{ matrix.service }}
        run: |
          npm ci
          npm test

      - name: Build image
        run: docker build -t ${{ matrix.service }}:${{ github.sha }} services/${{ matrix.service }}

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.service }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: '1'

      - name: Configure AWS
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ap-south-1

      - name: Push to ECR
        if: github.event_name == 'push'
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_ACCOUNT }}.dkr.ecr.ap-south-1.amazonaws.com
          docker tag  ${{ matrix.service }}:${{ github.sha }} ${{ secrets.ECR_ACCOUNT }}.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service }}:${{ github.sha }}
          docker push ${{ secrets.ECR_ACCOUNT }}.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service }}:${{ github.sha }}
